server:
  port: 8080
  #servlet上下文路径，默认/
  servlet:
    context-path: /im_sys
spring:
  datasource:
    name: im_sys
    #采用druid的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #url
    url: jdbc:mysql://39.101.170.233:3306/im_bird?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    #用户名
    username: root
    password: root
    #监控统计
    filters: stat,log4j
    initial-size: 2 #初始化连接
    max-idle: 10 #最大空闲连接数
    min-idle: 1 #最小空闲连接数
    max-active: 20 #最大活动连接
    #获取连接超时的等待时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-evict-runs-millis: 60000
    #一个连接在池中最小生存空间
    min-evictable-idle-time-millis: 300000
    #验证连接有效与否的SQL，不同数据配置不同
    validation-query: SELECT 'x'
    #指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将从池中去除
    test-while-idle: true
    #借出连接时不要测试，否则影响性能
    text-on-borrow: false
  redis:
    host: 39.101.170.233
  # springmvc 视图解析器扫描前缀与后缀为指定名称的路径
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  jackson:
    time-zone: Asia/Shanghai
mybatis:
  mapper-locations: classpath:com/lhq/mapper/*.xml
logging:
  level:
    com.lhq.mapper: debug

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.183.101:22122